const BioOfMohitChowdhury = () => (
  <div className="max-w-screen-md mx-auto px-12 py-8 bg-[#E3F6FC] rounded-md mt-8 shadow">
    <h2 className="text-2xl font-bold text-[#2D8CBB] mb-2 text-center">Bio of Dr. Mohit Chowdhury</h2>
    <div className="mx-auto mb-4" style={{ height: '4px', width: '60px', background: '#FFCE00', borderRadius: '2px' }} />
    <p className="text-gray-800 leading-relaxed text-justify">
      Dr. Mohit Chowdhury is a public health scientist, academic leader, and educator with over 15 years of experience in clinical medicine, epidemiological research, and global health program development. He currently serves as the <a href="https://asian-university.org/2024/07/30/dr-mohiuddin-ahsanul-kabir-chowdhury-appointed-as-takeda-chair-in-public-health/" target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">Associate Dean of Natural Sciences, Takeda Chair of Public Health</a>, and Program Director of the Public Health Program at the Asian University for Women (AUW), where he also holds the position of Associate Professor of Public Health.<br /><br />
      Dr. Chowdhury earned his PhD in Epidemiology from the Arnold School of Public Health at the University of South Carolina, USA. His doctoral research focused on the association of prenatal exposure to NSAIDs and acetaminophen with autism spectrum disorders in children. He also holds a Master of Public Health (MPH) degree with the highest distinction from the <a href="https://bracjpgsph.org/" target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">James P Grant School of Public Health</a> at BRAC University and an MBBS from Chittagong Medical College.<br /><br />
      With a diverse research portfolio, Dr. Chowdhury has led and contributed to over 30 funded projects addressing maternal and child health, cancer care, antimicrobial resistance, health service quality, disability, gender-based violence, and infectious diseases, particularly among displaced and underserved populations. He is currently a principal or co-investigator on major projects funded by organizations including the WHO, Swiss Red Cross, NIH (Global Health Catalyst), and NSF.<br /><br />
      Dr. Chowdhury has <a href="https://scholar.google.com/citations?user=ax5t0IAAAAAJ&hl=en" target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">published</a> extensively in international peer-reviewed journals, including The Lancet Oncology, Journal of Women's Health, BMJ Open, and PLOS ONE, and has collaborated with global initiatives such as the Global Burden of Disease Study. His research contributions reflect a commitment to equity, implementation science, and context-sensitive health interventions.<br /><br />
      In addition to his academic and research leadership, Dr. Chowdhury is a passionate educator. At AUW, he has developed and taught a wide range of undergraduate courses, including Epidemiology, Environmental Health, Biostatistics, Maternal and Child Health, Social and Behavioral Science, and Global Health Policy. He also holds adjunct faculty appointments at the BRAC James P Grant School of Public Health and Chittagong Veterinary and Animal Sciences University.<br /><br />
      Dr. Chowdhury's vision centres on strengthening public health education, advancing implementation research in South Asia, and mentoring the next generation of global health leaders, particularly women from marginalized communities.
    </p>
  </div>
);

export default BioOfMohitChowdhury; 